// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syimuaeckuvzfxypfaoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5aW11YWVja3V2emZ4eXBmYW9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MDM3NjUsImV4cCI6MjA2ODI3OTc2NX0.ZUMnOY436_T_Q3W3MdazINrR21tj472lgWYY2SB7GYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});